targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - unnecessary_raw_strings
      shelf_routing_generator:router:
        generate_for:
          - example/**
      shelf_routing_generator:
        generate_for:
          - example/**

builders:
  shelf_routing_generator:router:
    import: package:shelf_routing_generator/run_router_builder.dart
    builder_factories: [ 'runRouterBuilder' ]
    applies_builders: [ 'source_gen:combining_builder' ]
    build_extensions: { '.dart': [ '.router.g.part' ] }
    auto_apply: dependents
    build_to: cache

  shelf_routing_generator:
    import: package:shelf_routing_generator/run_routing_builder.dart
    builder_factories: [ 'runRoutingBuilder' ]
    applies_builders: [ 'source_gen:combining_builder' ]
    build_extensions: { '.dart': [ '.routing.g.part' ] }
    auto_apply: dependents
    build_to: cache
