name: shelf_routing_generator
description: Generator for routing class methods with support for path parameters, query parameters, body and headers.
repository: https://github.com/BreX900/mek-packages
issue_tracker: https://github.com/BreX900/mek-packages/issues
homepage: https://github.com/BreX900/mek-packages/tree/main/shelf_packages/shelf_routing_generator
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

scripts:
  publish: dart pub publish
  runner:watch: dart run build_runner watch --delete-conflicting-outputs --verbose

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_routing: ^0.1.0

  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.3.0
  dart_style: ^2.3.4

  collection: ^1.18.0
  recase: ^4.1.0
  glob: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  mek_lints: ^4.0.0

  test: ^1.25.0
  mocktail: ^1.0.2
  build_test: ^2.2.2

  decimal: ^2.3.3
  build_runner: ^2.4.7

dependency_overrides:
  shelf_routing: { path: ../shelf_routing }
